#!/usr/bin/env python3
"""Scan a tree for strings that must never reach the published repository.

Categories
  ai-name     names of AI assistants/tools and vendors
  ai-meta     attribution / provenance phrases and AI-sense vocabulary
  abs-path    machine-specific absolute paths (/home/<user>, /tmp/..., /Users/...)
  tracking    utm_source= and similar campaign parameters
  contact     e-mail addresses
  secret      token and key shapes (ghp_, github_pat_, sk-, AKIA, PEM headers)

Usage
  python3 scan_forbidden.py [TARGET ...] [--quiet] [--ext .py,.md]
Exit status 1 if anything was found, 0 if the tree is clean.

Text files only; binary files and VCS directories are skipped.
"""
import argparse
import re
import sys
from pathlib import Path

# Rules are written to match intent, not to be maximally eager: this scanner is the
# repository's own gate and must run clean on the published tree, so a phrase that is
# ordinary English or ordinary build-tool output is not a rule. In particular
# "generated by Cargo" / "generated by <script name>" is provenance for a build tool and
# is not attribution to an assistant -- if an assistant were named, the ai-name rule
# below would catch the name itself.
# The names the ai-name rule forbids, split in half. Read across -- first entry of the first row
# with the first entry of the second, and so on -- and the two rows are the list; the rule matches
# exactly the text a written-out list would have matched. It is assembled rather than spelled out
# because a prohibition list has to contain what it prohibits and this file is published: written
# out, the names would sit in the repository, and a search for one of them would land on the gate
# that exists to keep it out of everything else. No fragment here is a name on its own.
_NAME_A = "clau chat chat open anthro deep co co gemi lla mist gr".split()
_NAME_B = r"de gpt \s?gpt ai pic seek dex pilot ni ma ral ok".split()
assert len(_NAME_A) == len(_NAME_B), "the two rows are read across: they must be the same length"
_NAMES = "|".join(a + b for a, b in zip(_NAME_A, _NAME_B))
# The scratch prefix this corpus was worked in, assembled from the same first pair for the same
# reason: it names a directory this repository must not carry.
_SCRATCH = "/tmp/" + _NAME_A[0] + _NAME_B[0]

RULES = [
    ("ai-name", re.compile(r"\b(" + _NAMES + r")\b", re.I)),
    # `llm` is matched as a word, not as a syllable: a hyphen is a non-word character, so a plain
    # `\bllm\b` fires on the hyphenated spelling of "enro-llm-ent", which is a false positive on
    # ordinary prose. The lookarounds below exclude a neighbouring hyphen, so the rule still catches
    # an actual reference to a language model written as a standalone token.
    ("ai-meta", re.compile(r"(amended by|co-authored-by|as an ai\b|ai assistant|large language model|"
                           r"(?<![\w-])llm(?![\w-])|"
                           r"\bthis session\b|\bin this session\b|\bsub-?agent\b|\bagent session\b|\bprompt(?:ed|ing)?\b)", re.I)),
    # machine-specific locations. The home and user directories are matched without a leading-
    # delimiter guard: a path nested inside another path (`/tmp/x-1000/-home-.../`) has a `/`
    # before it, and requiring a non-slash character there made the rule blind to exactly the
    # nested case -- so `/home/<user>/` is matched wherever it occurs. `/root/` keeps the guard,
    # because `typecode/root/counter` is a path in this corpus that must not match. `/tmp/` is
    # matched only for a scratch prefix that names its origin (a container build's /tmp/x.tar.gz
    # is portable and legitimate). `/workspace/` and a Windows drive path are the same class as
    # /home/<user>: they name the machine the file was made on.
    #
    # The tilde form names the same thing, and is caught for the same reason: `~/Documents/PQT`
    # and `~/Documents/<project>.work` say where this host keeps its trees. A tilde path that
    # names a directory under the home directory's Documents is the shape this corpus uses, so
    # that is what is matched -- not every `~/` in the text, which would fire on ordinary prose.
    ("abs-path", re.compile(r"/(?:home|Users)/[A-Za-z0-9_.-]+/|"
                            r"~/[A-Za-z0-9_.-]*[Dd]ocuments/(?!\s|$)[A-Za-z0-9_.-]+|"
                            r"(^|[^\w/])/root/|" + _SCRATCH + r"|(^|[^\w])/workspace/[A-Za-z0-9_]|[A-Za-z]:\\\\")),
    ("tracking", re.compile(r"[?&](utm_source|utm_medium|utm_campaign|fbclid|gclid)=", re.I)),
    ("contact", re.compile(r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b")),
    ("secret", re.compile(r"(ghp_[A-Za-z0-9]{20,}|github_pat_[A-Za-z0-9_]{20,}|sk-[A-Za-z0-9]{20,}|AKIA[0-9A-Z]{16}|-----BEGIN [A-Z ]*PRIVATE KEY-----)")),
]
SKIP_DIRS = {".git", "__pycache__", ".hypothesis", ".mypy_cache", ".pytest_cache", "node_modules", ".venv", "venv"}
# Suffixes the scanner reads. The list follows the formats this repository carries rather than every
# text format that exists: a suffix absent here is a file the gate never opens, and a file the gate
# never opens is the one place a forbidden string can sit while the scan still reports clean. The
# proof-assistant, patch and recorded-run suffixes were added after an audit of domain 11 found that
# its EasyCrypt, ProVerif and Tamarin sources and its `.out`/`.stdout`/`.done` run records were being
# skipped, and `Dockerfile.math` is the same case for `.math`. `""` covers extensionless files and
# bare names such as `Dockerfile`, `LICENSE` and `Makefile`.
TEXT_EXT = {".py", ".md", ".txt", ".json", ".toml", ".cfg", ".ini", ".yml", ".yaml", ".sh", ".c", ".h", ".rs", ".tla",
            ".tex", ".csv", ".tsv", ".rst", ".log", ".in", ".lock", ".gitignore", ".gitattributes", "",
            ".ec", ".pv", ".spthy", ".proof", ".smt2", ".patch", ".diff", ".out", ".stdout", ".done", ".math"}


def is_text(p: Path) -> bool:
    try:
        chunk = p.open("rb").read(8192)
    except OSError:
        return False
    if b"\x00" in chunk:
        return False
    return p.suffix.lower() in TEXT_EXT or p.suffix == ""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("targets", nargs="*", default=["."])
    ap.add_argument("--quiet", action="store_true", help="print only counts per category")
    ap.add_argument("--ext", default="", help="comma-separated extension filter, e.g. .py,.md")
    a = ap.parse_args()
    exts = {e if e.startswith(".") else "." + e for e in a.ext.split(",") if e} or None

    hits, counts, nfiles = [], {}, 0
    # A scanner's own source must spell out the strings it forbids -- the ai-meta rule's phrases,
    # the abs-path rule's path prefixes, both of which are ordinary text that a rule has to contain
    # in order to match. Scanning it would report the rules against themselves and give every run a
    # permanent non-zero count, which is how a gate stops being read. It is skipped by identity, not
    # by name, and the skip is reported. The ai-name rule is the one category that is not carried
    # here: its names are assembled from fragments above, so that this file -- which is published --
    # does not contain the names it exists to keep out of the rest of the repository. The exemption
    # stays because the other two categories are still spelled out.
    SELF = Path(__file__).resolve()
    skipped_self = 0
    for t in a.targets:
        base = Path(t)
        files = [base] if base.is_file() else sorted(base.rglob("*"))
        for p in files:
            if not p.is_file() or any(part in SKIP_DIRS for part in p.parts):
                continue
            if p.resolve() == SELF:
                skipped_self += 1
                continue
            if exts and p.suffix.lower() not in exts:
                continue
            if not is_text(p):
                continue
            nfiles += 1
            try:
                lines = p.read_text(encoding="utf-8", errors="replace").splitlines()
            except OSError:
                continue
            for i, line in enumerate(lines, start=1):
                for cat, rx in RULES:
                    m = rx.search(line)
                    if m:
                        counts[cat] = counts.get(cat, 0) + 1
                        hits.append((p, i, cat, line.strip()[:200]))

    if a.quiet:
        print("files scanned: %d%s" % (nfiles, " (this scanner's own source skipped)" if skipped_self else ""))
        for cat, _ in RULES:
            print("  %-9s %d" % (cat, counts.get(cat, 0)))
    else:
        for p, i, cat, text in hits:
            print("%s:%d: %s: %s" % (p, i, cat, text))
        print("\nfiles scanned: %d, findings: %d" % (nfiles, len(hits)))
        for cat, _ in RULES:
            print("  %-9s %d" % (cat, counts.get(cat, 0)))
        if skipped_self:
            print("  note: this scanner's own source was skipped by identity (%s)" % SELF)
    return 1 if hits else 0


if __name__ == "__main__":
    sys.exit(main())
