"""The q-ary lattice a normal-form instance defines, and the checks that it is the right one.

Section 3.3 of the design document names the hazard this module exists for: *a wrong lattice reduces
perfectly*. A transposed base, an off-by-one in a block, a stale ``qI`` term or a sign error all
produce a full-rank lattice of the right determinant, which BKZ then reduces happily, yielding a
root-Hermite factor that looks like every other root-Hermite factor. There is no downstream signal.

So the construction is not trusted on inspection. Two independent checks run on it — a *structural*
one (every row satisfies the modular relation) and a *volumetric* one (the determinant is exactly
``q**m``) — because they fail for different bugs, and a basis that passes both is one that the
remainder of the project can be built on.

**The construction, written out.** For ``b = A x + e (mod q)`` with ``A`` of shape ``m x n``, the
lattice is the set of vectors carrying both the samples and the secret::

    Lambda = { (A c + q z, c) : c in Z^n, z in Z^m }  subset of  Z^m x Z^n

generated by ``n`` rows ``(A^T, I_n)`` — one per secret coordinate, each producing a column of
``A`` — together with ``m`` rows ``(q I_m, 0)``. The determinant is ``q^m``.

The instance's own relation puts ``(b - e, x) = (A x + q z0, x)`` in the lattice, so the lattice
contains a vector whose first block is within ``|e|`` of the public ``b``. That is what makes the
secret findable, and it is what the planted-vector test verifies before any reduction runs.
"""

from __future__ import annotations

from typing import Any

import numpy as np

from ..problem.normal_form import NormalFormInstance
from ._exact import det_abs, solve_integer

#: Re-exported so callers validating a lattice do not have to reach into the engines layer, while
#: the implementation stays in exactly one place. Cross-check 6 of the project's battery, and the
#: single invariant most worth keeping: two engines can each return a self-consistent basis of a
#: *different* lattice, and nothing per-engine can see it.
from ..engines.base_engine import assert_same_lattice  # noqa: F401

__all__ = [
    "build_qary_basis",
    "build_primal_embedding_basis",
    "assert_basis_valid",
    "assert_same_lattice",
    "basis_determinant_abs",
]


def build_qary_basis(nf: NormalFormInstance) -> Any:
    """The lattice of ``(A c + q z, c)``: ``n`` secret rows plus ``m`` modular rows.

    Returns an ``fpylll.IntegerMatrix`` because that is what every engine consumes, and converting
    later would mean the object that was validated is not the object that was reduced.
    """
    from fpylll import IntegerMatrix

    n, m, q = nf.n, nf.m, nf.q
    dim = n + m
    basis = IntegerMatrix(dim, dim, int_type="mpz")

    # Top block: one row per secret coordinate. Row j is (column j of A, e_j) — placing a unit in
    # the secret block means the lattice carries the secret alongside the samples, so a short vector
    # recovers both the error and the secret rather than only the error.
    a = nf.a % q
    for j in range(n):
        for i in range(m):
            basis[j, i] = int(a[i, j])
        basis[j, m + j] = 1

    # Bottom block: the modular relations, q times each sample coordinate.
    for i in range(m):
        basis[n + i, i] = q

    return basis


def build_primal_embedding_basis(nf: NormalFormInstance, *, embedding_factor: int) -> Any:
    """Kannan embedding: the q-ary lattice plus a row carrying the target and a factor ``M``.

    The embedding is what turns "find the secret" into a unique-shortest-vector problem. The target
    row is ``(b, 0, M)``, so the vector

        ``(b, 0, M) - (b - e, x, 0) = (e, -x, M)``

    is in the embedded lattice and is short exactly when ``e`` and ``x`` are — which the normal form
    guarantees. ``M`` must be large enough that the embedding coordinate dominates the difference
    between the planted vector and any other lattice vector, and small enough that the planted
    vector stays shortest. `calibrate_embedding_factor` measures the right value rather than
    guessing it.
    """
    from fpylll import IntegerMatrix

    if embedding_factor < 1:
        raise ValueError(f"embedding_factor must be positive, got {embedding_factor}")

    n, m, q = nf.n, nf.m, nf.q
    base = build_qary_basis(nf)
    dim = n + m
    embedded = IntegerMatrix(dim + 1, dim + 1, int_type="mpz")

    for i in range(dim):
        for j in range(dim):
            embedded[i, j] = base[i, j]

    # The target row. Only the first block is filled: `b` lives in the sample coordinates.
    for i in range(m):
        embedded[dim, i] = int(nf.b[i] % q)
    embedded[dim, dim] = embedding_factor

    return embedded


def basis_determinant_abs(basis: Any) -> int:
    """``|det B|``, exactly, for a square basis given as rows.

    Exact integers throughout. A float determinant at these magnitudes rounds, and the determinant
    is one of the two checks that decide whether the lattice is the right one — a check that rounds
    is a check that can agree with a wrong basis.
    """
    rows = [[int(basis[i, j]) for j in range(basis.ncols)] for i in range(basis.nrows)]
    matrix = np.array(rows, dtype=object)
    return det_abs(matrix)


def assert_basis_valid(basis: Any, nf: NormalFormInstance) -> None:
    """Two independent checks that this is the lattice the instance describes.

    **Structural:** every row ``(u, w)`` satisfies ``u == A w (mod q)``. This is the definition, and
    it needs no derivation — a row that violates it is not in the lattice, whatever the matrix
    looks like.

    **Volumetric:** ``|det B| == q**m``. A different bug from the structural one: a basis could
    satisfy the relation row-by-row while spanning a sublattice or a superlattice, and only the
    volume catches that.

    They are run together because they fail independently, and the pair is what makes the check
    worth trusting rather than merely present.
    """
    n, m, q = nf.n, nf.m, nf.q
    if basis.nrows != n + m or basis.ncols != n + m:
        raise ValueError(
            f"basis is {basis.nrows}x{basis.ncols}, expected ({n + m})x({n + m}) "
            f"for n={n} secret coordinates and m={m} samples"
        )

    a = nf.a % q
    for row in range(n + m):
        u = np.array([int(basis[row, i]) for i in range(m)], dtype=np.int64)
        w = np.array([int(basis[row, m + j]) for j in range(n)], dtype=np.int64)
        if not np.array_equal(u % q, (a @ w) % q):
            raise AssertionError(
                f"row {row} is not in the lattice: its sample block does not equal A times its "
                f"secret block modulo q. This is the structural check, and it is the definition "
                f"rather than a derived property."
            )

    det = basis_determinant_abs(basis)
    expected = q**m
    if det != expected:
        raise AssertionError(
            f"|det B| = {det}, expected q**m = {expected}. The rows satisfy the modular relation "
            "but span a different volume, so this is a sublattice or superlattice rather than the "
            "intended lattice."
        )
