"""The dual lattice, and the distinguisher the dual attack runs on it.

The design document asks for both attack families because the estimator reports the **minimum over
both** as the claimed security level: testing one gives a one-sided picture, and the one-sided
picture can only ever be optimistic.

## The lattice

For the q-ary lattice ``Lambda = { A c + q z }`` in the sample space ``Z^m``, the dual is

    Lambda* = { y in Z^m : A^T y == 0 (mod q) }

a full-rank sublattice of ``Z^m`` of determinant ``q^n``. Its short vectors are what the dual attack
uses: for ``y`` in ``Lambda*``,

    <y, b> = <y, A s + e> = <A^T y, s> + <y, e> == <y, e> (mod q)

and since ``y`` is short and ``e`` is small, ``<y, e>`` is much smaller than ``q`` — so the inner
product is detectable rather than uniform. A genuinely uniform ``b`` gives a uniform inner product.
That contrast is the distinguisher.

## The basis, and why the two checks are independent

Using the pivot that the normal form already selects — ``n`` rows of ``A`` forming ``A1``,
invertible modulo ``q`` — every ``y`` splits into a pivot block and the rest, and

    A1^T y_pivot + A2^T y_rest == 0 (mod q)   =>   y_pivot == -(A2 A1^{-1})^T y_rest

so the lattice is generated by

* ``n`` rows ``q * e_i`` on the pivot coordinates, and
* ``m - n`` rows carrying a unit in one rest coordinate and ``-(A2 A1^{-1})^T`` on the pivots.

The determinant is ``q^n``, which is the check that the basis spans the right volume. The other
check — that every row annihilates the primal sample space modulo ``q`` — is the *definition*, and
needs no derivation.

**Both are required because they fail for different bugs.** A basis built from a wrong pivot still
satisfies the annihilation property on the rows it produces while spanning the wrong volume; a
basis with the right determinant can still have rows that are not in the dual at all. Neither check
alone would catch both, and a corrupted basis is exercised against each separately in the tests.
"""

from __future__ import annotations

import math
from dataclasses import dataclass

import numpy as np

from ..problem.normal_form import NormalFormInstance, choose_invertible_pivot, inverse_mod
from ._exact import det_abs

__all__ = [
    "dual_basis",
    "assert_dual_valid",
    "dual_dimension",
    "DistinguisherStatistic",
    "dual_distinguisher",
]


def dual_dimension(nf: NormalFormInstance) -> int:
    """The dual lattice's dimension, which is the sample count ``m`` — not ``n``."""
    return nf.m


def dual_basis(nf: NormalFormInstance):
    """A basis of ``{ y in Z^m : A^T y == 0 (mod q) }``, of determinant ``q^n``."""
    from fpylll import IntegerMatrix

    q, m, n = nf.q, nf.m, nf.n
    a = nf.a % q
    # The complement condition is deliberately *not* required here, unlike in the normal form.
    # There the complement rows become A2, and A' = A2 A1^-1 inherits their rank, so a deficient
    # complement silently gives a deficient base. Here the pivot is taken inside an
    # already-transformed base: the construction above is algebraically valid whatever rank the
    # remaining rows have, and its determinant is q^n either way. Requiring it would refuse pivots
    # that work.
    pivot = choose_invertible_pivot(a, q, require_complement_full_rank=False)
    rest = tuple(i for i in range(m) if i not in set(pivot))

    a1 = a[list(pivot)]
    a2 = a[list(rest)]
    t = (a2 @ inverse_mod(a1, q)) % q  # (m-n) x n

    basis = IntegerMatrix(m, m, int_type="mpz")
    # The modular rows: q on each pivot coordinate, nothing else. Any integer multiple of these
    # satisfies the congruence trivially.
    for i, row_index in enumerate(pivot):
        basis[i, row_index] = q
    # The kernel rows: a unit in one free coordinate and -(A2 A1^{-1})^T on the pivots, which is
    # what forces A^T y to vanish modulo q.
    for j, row_index in enumerate(rest):
        for i, pivot_index in enumerate(pivot):
            basis[n + j, pivot_index] = int((-t[j, i]) % q)
        basis[n + j, row_index] = 1
    return basis


def _sample_block(primal_basis, m: int) -> list[list[int]]:
    """The sample coordinates of each primal row, as integers."""
    return [
        [int(primal_basis[i, j]) for j in range(m)] for i in range(primal_basis.nrows)
    ]


def assert_dual_valid(dual, primal_basis, nf: NormalFormInstance) -> None:
    """Two independent checks. Each catches a bug the other cannot.

    **Annihilation:** every dual row is orthogonal modulo ``q`` to the sample block of every primal
    row. This is the definition of the dual, so it needs no derivation and a failure means the
    basis is not in the dual at all.

    **Volume:** ``|det D| == q^n``. A different failure entirely — a basis can annihilate the primal
    space perfectly while spanning a sublattice of it, and only the determinant sees that. The
    determinant is exact; a floating one compared against ``q^n`` would be a coin flip.
    """
    q, m, n = nf.q, nf.m, nf.n
    if dual.nrows != m or dual.ncols != m:
        raise ValueError(f"dual basis is {dual.nrows}x{dual.ncols}, expected {m}x{m}")

    samples = _sample_block(primal_basis, m)
    for i in range(m):
        y = np.array([int(dual[i, j]) for j in range(m)], dtype=np.int64)
        for row in samples:
            value = int(np.dot(y, np.array(row, dtype=np.int64)) % q)
            if value != 0:
                raise AssertionError(
                    f"dual row {i} is not orthogonal to a primal sample row modulo q: the inner "
                    f"product is {value}, expected 0. This is the definition of the dual lattice."
                )

    determinant = det_abs(np.array([[int(dual[i, j]) for j in range(m)] for i in range(m)], dtype=object))
    if determinant != q**n:
        raise AssertionError(
            f"|det D| = {determinant}, expected q^n = {q**n}. The rows annihilate the primal space "
            "correctly but span a different volume, so this is a sublattice or superlattice rather "
            "than the dual lattice."
        )


@dataclass(frozen=True, slots=True)
class DistinguisherStatistic:
    """The outcome of one dual distinguisher evaluation.

    ``advantage`` is measured against the *analytic* uniform expectation, and ``control_advantage``
    against genuinely uniform samples. The control is not optional: a statistic that fires on
    everything, including uniform noise, is a broken statistic that would otherwise read as a
    successful attack — the same reasoning as the sibling project's negative control, which turned
    out to be marking a set a correct probe *should* have fired on.
    """

    n_samples: int
    in_band: int
    expected_fraction: float
    observed_fraction: float
    advantage: float
    control_advantage: float
    dual_norm_squared: int

    @property
    def is_meaningful(self) -> bool:
        """A distinguisher is only evidence if it separates real from uniform, not merely from zero."""
        return self.advantage > abs(self.control_advantage)


def dual_distinguisher(
    vectors,
    sample,
    nf: NormalFormInstance,
    *,
    control_sample=None,
) -> DistinguisherStatistic:
    """Evaluate a family of dual vectors against one real sample and one uniform control.

    **The roles are the other way round from the obvious reading**, and getting that wrong makes the
    statistic vacuous. A single instance supplies exactly *one* real sample vector ``b``; what there
    are many of is short dual vectors ``y``. So the sample set is the vectors, not the samples, and
    ``n_samples`` below counts dual vectors tested.

    The test is whether ``|<y, b>|`` lands inside its band ``||y||_1 * B``. For the real relation
    ``<y, b> == <y, e'> (mod q)`` by construction, and ``|<y, e'>| <= ||y||_1 * B`` holds
    **exactly** — the bound is deterministic, not probabilistic — so every real vector lands inside.
    A uniform sample gives a residue that lands inside only with probability ``2*||y||_1*B / q``.

    That gap is the distinguisher, and it is why the control matters rather than being decoration:
    the statistic is trivially near 1 for real data, so a broken implementation would look like a
    perfect attack unless something known-uniform is run through the same code path.
    """
    k = nf.m
    q, bound = nf.q, nf.noise_bound

    def band_of(y) -> int:
        return bound * sum(abs(v) for v in y)

    def centred_inner(y, b) -> int:
        inner = sum(int(y[i]) * int(b[i]) for i in range(k)) % q
        return inner - q if inner > q // 2 else inner

    def evaluate(b) -> tuple[int, float, float]:
        inside = 0
        expected_total = 0.0
        for y in vectors:
            y = [int(v) for v in y]
            if len(y) != k:
                raise ValueError(f"dual vector has length {len(y)}, expected m={k}")
            band = band_of(y)
            if abs(centred_inner(y, b)) <= band:
                inside += 1
            expected_total += min(1.0, (2 * band + 1) / q)
        n = len(vectors)
        return inside, inside / n, expected_total / n

    in_band, observed, expected = evaluate(sample)
    advantage = observed - expected

    if control_sample is None:
        control_advantage = 0.0
    else:
        _, control_observed, _ = evaluate(control_sample)
        control_advantage = control_observed - expected

    shortest = min(
        (sum(int(v) * int(v) for v in y) for y in vectors), default=0
    )
    return DistinguisherStatistic(
        n_samples=len(vectors),
        in_band=in_band,
        expected_fraction=expected,
        observed_fraction=observed,
        advantage=advantage,
        control_advantage=control_advantage,
        dual_norm_squared=shortest,
    )
