#!/usr/bin/env python3
"""
gen_n7_votes.py -- generate qpt128_quorum_n7.spthy, a SECOND, deliberately
different Tamarin abstraction of the QPT-128 / CE-QS profile-B0 quorum
certificate for N = 7, q = 5 (2q-N = 3).

Differences from qpt128_quorum.spthy (N = 4):
  * no cryptographic terms at all: the signature scheme is replaced by an
    ideal authenticated vote fact  !Vote(seat, K, v)  that only the seat
    itself (Vote_honest) or the adversary holding a corrupted seat
    (Vote_adversary) can create.  This is the "ideal signature" abstraction;
    the N = 4 model uses the symbolic `signing` theory instead.
  * corruption creates a persistent capability !Corrupted(s) rather than
    leaking a key term.
  * a certificate is any 5-subset of the 7 seats (21 explicit rules); each
    rule also records a single Signers(c, a1..a5) action so that the
    "five distinct signers" lemma needs one formula instance per rule.
  * the threshold constants are 3 (B: three distinct corrupt seats; E1: at
    most two corrupt seats => no conflict; E2: exactly three => conflict).
"""

import itertools
import sys

N, Q = 7, 5
THR = 2 * Q - N
SEATS = ["'s%d'" % i for i in range(N)]

out = []
w = out.append

w("""/*
 * QPT-128 / CE-QS profile B0 -- SECOND abstraction (ideal authenticated votes)
 * N = %d, q = %d, 2q-N = %d.   GENERATED by gen_n7_votes.py -- do not edit.
 *
 * Signatures are abstracted as authenticated vote facts !Vote(s,K,v) that only
 * seat s (honestly, one candidate per K) or the adversary holding a corrupted
 * seat can create.  A certificate is any %d-subset of the %d seats; the %d
 * subsets are explicit rules.  Lemmas A..E as in qpt128_quorum.spthy with the
 * threshold constant %d.
 */

theory QPT128_Quorum_N%d_q%d_Votes
begin

// One registration rule per seat: the seat universe is fixed by construction
// (no seat-name disjunction for Tamarin to case-split at every Register node).
%s

restriction OnlyOnce:
  "All x #i #j. OnlyOnce(x)@i & OnlyOnce(x)@j ==> #i = #j"

rule Corrupt:
    [ !Seat($s) ]
  --[ Corrupt($s) ]->
    [ !Corrupted($s) ]

// honest vote: one candidate per coordinate
rule Vote_honest:
    [ !Seat($s), In(<K, v>) ]
  --[ Signed($s, K, v) ]->
    [ !Vote($s, K, v) ]

restriction HonestSignsOneCandidatePerCoordinate:
  "All s K v1 v2 #i #j. Signed(s, K, v1)@i & Signed(s, K, v2)@j ==> v1 = v2"

// adversary vote in the name of a corrupted seat: anything, any time
rule Vote_adversary:
    [ !Corrupted($s), In(<K, v>) ]
  --[ AdvSigned($s, K, v) ]->
    [ !Vote($s, K, v) ]
""" % (N, Q, THR, Q, N, len(list(itertools.combinations(range(N), Q))), THR,
       N, Q,
       "\n".join("rule Register_%d:\n    [ ]\n  --[ Register(%s), OnlyOnce(<'reg', %s>) ]->\n    [ !Seat(%s) ]\n"
                 % (i, s, s, s) for i, s in enumerate(SEATS))))

for combo in itertools.combinations(range(N), Q):
    name = "Accept_" + "".join(str(i) for i in combo)
    seats = [SEATS[i] for i in combo]
    prem = ", ".join("!Vote(%s, K, v)" % s for s in seats)
    ver = ", ".join("Verified(%s, K, v)" % s for s in seats)
    signers = ", ".join("!CertSig(~c, K, v, %s)" % s for s in seats)
    w("""
rule %s:
    [ %s, Fr(~c) ]
  --[ Accept(~c, K, v), Signers(~c, %s), %s ]->
    [ %s ]""" % (name, prem, ", ".join(seats), ver, signers))

w("""

// A certificate is recorded as one !CertSig(c, K, v, seat) fact per signer, so
// extraction matches the shared seat of two certificates in a single premise
// pair (105 x 105 sources instead of a !Cert x !Signer product per side).
// [no_precomp]: these 105-source premises are resolved lazily (D1, C3 only).
rule Extract:
    [ !CertSig(c1, K, v1, s)[no_precomp], !CertSig(c2, K, v2, s)[no_precomp] ]
  --[ Evidence(s, K, v1, v2), Neq(v1, v2) ]->
    [ ]

restriction Neq:
  "All x y #i. Neq(x, y)@i ==> not(x = y)"

/* ================================================================== */

lemma sanity_honest_certificate:
  exists-trace
  "Ex c K v #i. Accept(c, K, v)@i & not(Ex s #k. Corrupt(s)@k)"
""")

A = ["a%d" % i for i in range(1, Q + 1)]
ver5 = " & ".join("Verified(%s, K, v)@i" % a for a in A)
neq5 = " & ".join("not(%s = %s)" % (x, y) for x, y in itertools.combinations(A, 2))
auth5 = "\n       & ".join(
    "((Ex #k. Signed(%s, K, v)@k & #k < #i) | (Ex #k. Corrupt(%s)@k & #k < #i))" % (a, a)
    for a in A)

w("""
// A.1 every accepted certificate names %d pairwise-distinct signers
lemma A1_distinct_signers:
  "All c K v #i. Accept(c, K, v)@i ==>
     Ex %s. Signers(c, %s)@i & %s
       & %s"

// A.2 every verified signer either honestly signed (K,v) or was corrupt before
lemma A2_signer_authorized [reuse]:
  "All s c K v #i. Accept(c, K, v)@i & Verified(s, K, v)@i ==>
       (Ex #k. Signed(s, K, v)@k & #k < #i)
     | (Ex #k. Corrupt(s)@k & #k < #i)"

// A (combined)
lemma A_acceptance_authorized:
  "All c K v #i. Accept(c, K, v)@i ==>
     Ex %s. Signers(c, %s)@i & %s
       & %s
       & %s"

// D.2 every seat in the intersection of two conflicting certificates is corrupt
lemma D2_intersection_seats_corrupt [reuse]:
  "All s c1 c2 K v1 v2 #i #j.
     Accept(c1, K, v1)@i & Accept(c2, K, v2)@j & not(v1 = v2)
     & Verified(s, K, v1)@i & Verified(s, K, v2)@j
     ==> Ex #k. Corrupt(s)@k & (#k < #i | #k < #j)"

// D.2b unordered corollary of D.2, used by B/C/E1: without the (k<i | k<j)
//      disjunction Tamarin needs no case split per shared seat (441 rule pairs).
lemma D2b_intersection_seats_corrupt_unordered [reuse]:
  "All s c1 c2 K v1 v2 #i #j.
     Accept(c1, K, v1)@i & Accept(c2, K, v2)@j & not(v1 = v2)
     & Verified(s, K, v1)@i & Verified(s, K, v2)@j
     ==> Ex #k. Corrupt(s)@k"

// D.1 every seat named by extraction was corrupted before the extraction
lemma D1_non_frameability [hide_lemma=A2_signer_authorized]:
  "All s K v1 v2 #i. Evidence(s, K, v1, v2)@i
     ==> Ex #k. Corrupt(s)@k & #k < #i"

// B a conflicting pair needs >= 2q-N = %d distinct corrupt seats
lemma B_conflict_needs_2qN_corrupt [hide_lemma=A2_signer_authorized, hide_lemma=D2_intersection_seats_corrupt]:
  "All c1 c2 K v1 v2 #i #j.
     Accept(c1, K, v1)@i & Accept(c2, K, v2)@j & not(v1 = v2)
     ==> Ex s1 s2 s3 #k #l #m. Corrupt(s1)@k & Corrupt(s2)@l & Corrupt(s3)@m
           & not(s1 = s2) & not(s1 = s3) & not(s2 = s3)"

// C.1 non-empty intersection
lemma C1_intersection_nonempty [hide_lemma=A2_signer_authorized, hide_lemma=D2_intersection_seats_corrupt]:
  "All c1 c2 K v1 v2 #i #j.
     Accept(c1, K, v1)@i & Accept(c2, K, v2)@j & not(v1 = v2)
     ==> Ex s. Verified(s, K, v1)@i & Verified(s, K, v2)@j"

// C.3 evidence reachable
lemma C3_evidence_reachable [hide_lemma=A2_signer_authorized, hide_lemma=D2_intersection_seats_corrupt, hide_lemma=D2b_intersection_seats_corrupt_unordered]:
  exists-trace
  "Ex s K v1 v2 #i. Evidence(s, K, v1, v2)@i"

// E.1 with at most 2q-N-1 = %d corrupt seats there is no conflicting pair
lemma E1_below_threshold_no_conflict [hide_lemma=A2_signer_authorized, hide_lemma=D2_intersection_seats_corrupt]:
  "(All s1 s2 s3 #k #l #m. Corrupt(s1)@k & Corrupt(s2)@l & Corrupt(s3)@m
      ==> (s1 = s2 | s1 = s3 | s2 = s3))
   ==> not(Ex c1 c2 K v1 v2 #i #j.
             Accept(c1, K, v1)@i & Accept(c2, K, v2)@j & not(v1 = v2))"

// E.2 with exactly 2q-N = %d corrupt seats a conflicting pair exists
lemma E2_at_threshold_conflict_exists [hide_lemma=A2_signer_authorized, hide_lemma=D2_intersection_seats_corrupt, hide_lemma=D2b_intersection_seats_corrupt_unordered]:
  exists-trace
  "Ex c1 c2 K v1 v2 s1 s2 s3 #i #j #k #l #m.
     Accept(c1, K, v1)@i & Accept(c2, K, v2)@j & not(v1 = v2)
     & Corrupt(s1)@k & Corrupt(s2)@l & Corrupt(s3)@m
     & not(s1 = s2) & not(s1 = s3) & not(s2 = s3)
     & (All s #n. Corrupt(s)@n ==> (s = s1 | s = s2 | s = s3))"

// C.2 (stronger) the intersection has >= 2q-N = %d seats  (proved last).
//     Stated as "for any two signers s,t of the first certificate there is a
//     common signer u outside {s,t}" (s,t guarded by Verified@i), which is
//     equivalent to |intersection| >= 3 and avoids a 3-way disjunction whose
//     trivially-true instances Tamarin would case-split.
lemma C2_intersection_at_least_2qN [hide_lemma=A2_signer_authorized, hide_lemma=D2_intersection_seats_corrupt]:
  "All c1 c2 K v1 v2 s t #i #j.
     Accept(c1, K, v1)@i & Accept(c2, K, v2)@j & not(v1 = v2)
     & Verified(s, K, v1)@i & Verified(t, K, v1)@i
     ==> Ex u. Verified(u, K, v1)@i & Verified(u, K, v2)@j & not(u = s) & not(u = t)"

end
""" % (Q, " ".join(A), ", ".join(A), ver5, neq5,
       " ".join(A), ", ".join(A), ver5, neq5, auth5,
       THR, THR - 1, THR, THR))

path = sys.argv[1] if len(sys.argv) > 1 else "qpt128_quorum_n7.spthy"
with open(path, "w") as f:
    f.write("".join(out))
print("wrote", path)
